/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var messages_robocup_ssl_detection_pb = require('./messages_robocup_ssl_detection_pb.js');
var messages_robocup_ssl_geometry_pb = require('./messages_robocup_ssl_geometry_pb.js');
goog.exportSymbol('proto.SSL_WrapperPacket', null, global);
goog.exportSymbol('proto.Timestamp', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Timestamp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Timestamp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Timestamp.displayName = 'proto.Timestamp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Timestamp.prototype.toObject = function(opt_includeInstance) {
  return proto.Timestamp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Timestamp} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Timestamp.toObject = function(includeInstance, msg) {
  var f, obj = {
    unixTimestamp: msg.getUnixTimestamp()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Timestamp}
 */
proto.Timestamp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Timestamp;
  return proto.Timestamp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Timestamp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Timestamp}
 */
proto.Timestamp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUnixTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Timestamp} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Timestamp.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Timestamp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Timestamp.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getUnixTimestamp();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Timestamp} The clone.
 */
proto.Timestamp.prototype.cloneMessage = function() {
  return /** @type {!proto.Timestamp} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 unix_timestamp = 1;
 * @return {number}
 */
proto.Timestamp.prototype.getUnixTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.Timestamp.prototype.setUnixTimestamp = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SSL_WrapperPacket = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SSL_WrapperPacket, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SSL_WrapperPacket.displayName = 'proto.SSL_WrapperPacket';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SSL_WrapperPacket.prototype.toObject = function(opt_includeInstance) {
  return proto.SSL_WrapperPacket.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SSL_WrapperPacket} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SSL_WrapperPacket.toObject = function(includeInstance, msg) {
  var f, obj = {
    detection: (f = msg.getDetection()) && messages_robocup_ssl_detection_pb.SSL_DetectionFrame.toObject(includeInstance, f),
    geometry: (f = msg.getGeometry()) && messages_robocup_ssl_geometry_pb.SSL_GeometryData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SSL_WrapperPacket}
 */
proto.SSL_WrapperPacket.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SSL_WrapperPacket;
  return proto.SSL_WrapperPacket.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SSL_WrapperPacket} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SSL_WrapperPacket}
 */
proto.SSL_WrapperPacket.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new messages_robocup_ssl_detection_pb.SSL_DetectionFrame;
      reader.readMessage(value,messages_robocup_ssl_detection_pb.SSL_DetectionFrame.deserializeBinaryFromReader);
      msg.setDetection(value);
      break;
    case 2:
      var value = new messages_robocup_ssl_geometry_pb.SSL_GeometryData;
      reader.readMessage(value,messages_robocup_ssl_geometry_pb.SSL_GeometryData.deserializeBinaryFromReader);
      msg.setGeometry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.SSL_WrapperPacket} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SSL_WrapperPacket.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SSL_WrapperPacket.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.SSL_WrapperPacket.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getDetection();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      messages_robocup_ssl_detection_pb.SSL_DetectionFrame.serializeBinaryToWriter
    );
  }
  f = this.getGeometry();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      messages_robocup_ssl_geometry_pb.SSL_GeometryData.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.SSL_WrapperPacket} The clone.
 */
proto.SSL_WrapperPacket.prototype.cloneMessage = function() {
  return /** @type {!proto.SSL_WrapperPacket} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional SSL_DetectionFrame detection = 1;
 * @return {proto.SSL_DetectionFrame}
 */
proto.SSL_WrapperPacket.prototype.getDetection = function() {
  return /** @type{proto.SSL_DetectionFrame} */ (
    jspb.Message.getWrapperField(this, messages_robocup_ssl_detection_pb.SSL_DetectionFrame, 1));
};


/** @param {proto.SSL_DetectionFrame|undefined} value  */
proto.SSL_WrapperPacket.prototype.setDetection = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.SSL_WrapperPacket.prototype.clearDetection = function() {
  this.setDetection(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.SSL_WrapperPacket.prototype.hasDetection = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SSL_GeometryData geometry = 2;
 * @return {proto.SSL_GeometryData}
 */
proto.SSL_WrapperPacket.prototype.getGeometry = function() {
  return /** @type{proto.SSL_GeometryData} */ (
    jspb.Message.getWrapperField(this, messages_robocup_ssl_geometry_pb.SSL_GeometryData, 2));
};


/** @param {proto.SSL_GeometryData|undefined} value  */
proto.SSL_WrapperPacket.prototype.setGeometry = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.SSL_WrapperPacket.prototype.clearGeometry = function() {
  this.setGeometry(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.SSL_WrapperPacket.prototype.hasGeometry = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
