/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var messages_robocup_ssl_detection_pb = require('./messages_robocup_ssl_detection_pb.js');
goog.exportSymbol('proto.Log_Frame', null, global);
goog.exportSymbol('proto.Refbox_Log', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Log_Frame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Log_Frame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Log_Frame.displayName = 'proto.Log_Frame';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Log_Frame.prototype.toObject = function(opt_includeInstance) {
  return proto.Log_Frame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Log_Frame} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Log_Frame.toObject = function(includeInstance, msg) {
  var f, obj = {
    frame: (f = msg.getFrame()) && messages_robocup_ssl_detection_pb.SSL_DetectionFrame.toObject(includeInstance, f),
    refboxCmd: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Log_Frame}
 */
proto.Log_Frame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Log_Frame;
  return proto.Log_Frame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Log_Frame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Log_Frame}
 */
proto.Log_Frame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new messages_robocup_ssl_detection_pb.SSL_DetectionFrame;
      reader.readMessage(value,messages_robocup_ssl_detection_pb.SSL_DetectionFrame.deserializeBinaryFromReader);
      msg.setFrame(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefboxCmd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Log_Frame} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Log_Frame.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Log_Frame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Log_Frame.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getFrame();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      messages_robocup_ssl_detection_pb.SSL_DetectionFrame.serializeBinaryToWriter
    );
  }
  f = jspb.Message.getField(this, 2);
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Log_Frame} The clone.
 */
proto.Log_Frame.prototype.cloneMessage = function() {
  return /** @type {!proto.Log_Frame} */ (jspb.Message.cloneMessage(this));
};


/**
 * required SSL_DetectionFrame frame = 1;
 * @return {!proto.SSL_DetectionFrame}
 */
proto.Log_Frame.prototype.getFrame = function() {
  return /** @type{!proto.SSL_DetectionFrame} */ (
    jspb.Message.getWrapperField(this, messages_robocup_ssl_detection_pb.SSL_DetectionFrame, 1, 1));
};


/** @param {proto.SSL_DetectionFrame|undefined} value  */
proto.Log_Frame.prototype.setFrame = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.Log_Frame.prototype.clearFrame = function() {
  this.setFrame(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Log_Frame.prototype.hasFrame = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string refbox_cmd = 2;
 * @return {string}
 */
proto.Log_Frame.prototype.getRefboxCmd = function() {
  return /** @type {string} */ (!this.hasRefboxCmd() ? "" : jspb.Message.getField(this, 2));
};


/** @param {string|undefined} value  */
proto.Log_Frame.prototype.setRefboxCmd = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.Log_Frame.prototype.clearRefboxCmd = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.Log_Frame.prototype.hasRefboxCmd = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Refbox_Log = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Refbox_Log.repeatedFields_, null);
};
goog.inherits(proto.Refbox_Log, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Refbox_Log.displayName = 'proto.Refbox_Log';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Refbox_Log.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Refbox_Log.prototype.toObject = function(opt_includeInstance) {
  return proto.Refbox_Log.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Refbox_Log} msg The msg instance to transform.
 * @return {!Object}
 */
proto.Refbox_Log.toObject = function(includeInstance, msg) {
  var f, obj = {
    logList: jspb.Message.toObjectList(msg.getLogList(),
    proto.Log_Frame.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Refbox_Log}
 */
proto.Refbox_Log.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Refbox_Log;
  return proto.Refbox_Log.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Refbox_Log} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Refbox_Log}
 */
proto.Refbox_Log.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Log_Frame;
      reader.readMessage(value,proto.Log_Frame.deserializeBinaryFromReader);
      msg.getLogList().push(value);
      msg.setLogList(msg.getLogList());
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.Refbox_Log} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.Refbox_Log.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Refbox_Log.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.Refbox_Log.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getLogList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Log_Frame.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.Refbox_Log} The clone.
 */
proto.Refbox_Log.prototype.cloneMessage = function() {
  return /** @type {!proto.Refbox_Log} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Log_Frame log = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.Log_Frame>}
 */
proto.Refbox_Log.prototype.getLogList = function() {
  return /** @type{!Array.<!proto.Log_Frame>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Log_Frame, 1));
};


/** @param {Array.<!proto.Log_Frame>} value  */
proto.Refbox_Log.prototype.setLogList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.Refbox_Log.prototype.clearLogList = function() {
  this.setLogList([]);
};


goog.object.extend(exports, proto);
